version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www
    networks:
      - net      
  php:
    image: php:7.4-fpm
    container_name: php7.4-fpm
    restart: always
    volumes:
      - ./web:/var/www
    networks:
      - net
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: danglyjp
      MYSQL_ROOT_PASSWORD: 123 # root pass
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
        - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql 
    ports:
      - 8080:80
    networks:
      - net
networks:
  net:
    driver: bridge
